function [Ddate, Power_Wind_Farm, Wind_hub, Power_Wave_Farm]= power_supply_fun(n_turbines, n_WECs, soil_losses)
plotOn= 0; %Set to 1 to make plots. Set to 0 to not plot

%input data of wind speed at every hour of year 
%Fingersh model

%Eureka, CA buoy

% get data
% %YY  MM DD hh mm WDIR WSPD GDR GST GTIME
% %yr  mo dy hr mn degT m/s degT m/s hhmm
% data_2009= dlmread('buoy_44020_nantucketSound_wind_data_2009.txt');
% data_2010= dlmread('buoy_44020_nantucketSound_wind_data_2010.txt');
% data_2011= dlmread('buoy_44020_nantucketSound_wind_data_2011.txt');
% data_2012= dlmread('buoy_44020_nantucketSound_wind_data_2012.txt');
% data_2013= dlmread('buoy_44020_nantucketSound_wind_data_2013.txt');
% data_2014= dlmread('buoy_44020_nantucketSound_wind_data_2014.txt');
% 



%%%%%%%%%%%%%%%%%%%%%%%%% WAVE DATA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% text files have the format:
% Column indices
%  1    2  3  4  5  6    7     8    9     10     11 12    13     14    15   16    17   18
% #YY  MM DD hh mm WDIR WSPD GST  WVHT   DPD   APD MWD   PRES  ATMP  WTMP  DEWP  VIS  TIDE
% #yr  mo dy hr mn degT m/s  m/s     m   sec   sec deg    hPa  degC  degC  degC  nmi    f

% DPD is Dominant wave period (seconds) is the period with the maximum wave energy
% APD is Average wave period (seconds) of all waves during the 20-minute period.
% See https://www.ndbc.noaa.gov/measdes.shtml

% Sandia WEC power curve data seems to use DPD

% data_2015= dlmread('buoy_46022_Eureka_2015.txt'); % a few days of missing data
% data_2016= dlmread('buoy_46022_Eureka_2016.txt');
data_2017= dlmread('buoy_46022_Eureka_2017.txt');
%data_2018= dlmread('buoy_46022_Eureka_2018.txt'); % missing or bad wave data starting 5/8/2018 to end of year

data= data_2017; %[data_2016; data_2017]; % add data together

date = [data(:,1:5) zeros(length(data(:,1)),1)];

    
%%

ddate = datenum(date); % date is [yr month day hr min sec]

windSpeed= data(:,7); %mean wind speed in 10 min period [m/s]
 
H_Eureka= data(:,9);
Tp_Eureka= data(:,10);

% Correct missing data
% Hs(4870:4961)= Hs([4870:4961]-92);
% Hs(9714)= Hs(9713);
% Hs(9716)= Hs(9715);
% 
% Tp(4870:4961)= Tp([4870:4961]-92);
% Tp(9714)= Tp(9713);
% Tp(9716)= Tp(9715);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Get wind power for each wind speed

%input table that relates each turbine power output to wind speed
%ASSUME ALL POWER/LOSSES SCALABLE WITH WIND TURBINE CAPACITY
%Accounts for 12.5% power losses
[U, P]= turbinePowerCurve(6, soil_losses); %power output of a turbine with capacity 6 MW
P= n_turbines.*P; %estimate total farm power for given wind speed

%Farm output power
%Buoy data is at sea level. Make adjustment according to Fingersh
hubHt= 97; %Changed to 97m for 6MW turbine hub height by Beiter (Maha 3/25/2019) - from NREL: 90, from Cape Wind.org: 87 [m]
sheer= .11; %Maha: 0.11. Valid range 0.08-0.14. Fingersh: 0.143;
instrument_ht= 5; %meters above sea level
wind_hub_Eureka= (hubHt/instrument_ht)^sheer.*windSpeed; %from Fingersh 

power_wind_farm= interp1(U, P, wind_hub_Eureka); %power generated by farm at each hour [MW]

%account for roughly +/- 1 m/s wind speed over farm [similar to Berberis Negra] 
%(.7.*interp1(U, P, wind_hub) + .15.*interp1(U, P, wind_hub+2) + .15.*interp1(U, P,wind_hub-.5))./1000;


%% Get wave power for each sea state

[T, H, Pwave]= WEC_PowerCurve;
Pwave= n_WECs.*Pwave; % WEC power for given T and H
power_wave_farm= interp2(T,H,Pwave, Tp_Eureka, H_Eureka)./1000; %[MW]

power_wave_farm( isnan(power_wave_farm) )= 0;


%%

if plotOn== 1
    figure;
    plot(ddate, power_wind_farm); hold on;
    plot(ddate, power_wave_farm);
    %'yyyy-mm-dd'
    datetick('x','yyyy-mm-dd')
    xlabel('index of year - 10 min intervals');
    ylabel('Wind farm power (MW)');
    title('Wind farm power over year');
end

% Expect CF~37.1% from  http://www.governorswindenergycoalition.org/?p=4027
% Tegan: CF~39% wind farm

% Outputs
Ddate= ddate;          
Power_Wind_Farm= power_wind_farm;
Wind_hub= wind_hub_Eureka;
Power_Wave_Farm= power_wave_farm;
Power_Combined= Power_Wind_Farm + Power_Wave_Farm;

CF_wind_alone= mean(Power_Wind_Farm)/max(Power_Wind_Farm);
CF_wave_alone= mean(Power_Wave_Farm)/max(Power_Wave_Farm);
CF_combined= mean(Power_Combined)/max(Power_Combined);

end